baseURL: "https://example.com"
languageCode: "en-us"
title: "Harlon Times"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "https://twitter.com/harlontimes"
  github: "https://github.com/HarlonTimes/harlon-times-website"
  instagram: "https://www.instagram.com/harlontimes/"
  linkedin: ""
  dribbble: ""
  youtube: ""
taxonomies:
  author: authors
