baseURL: "https://harlontimes.com"
languageCode: "en-us"
title: "Harlon Times"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "https://twitter.com/harlontimes"
  instagram: "https://www.instagram.com/harlontimes"
  youtube: "https://youtube.com/channel/UCPI5hnOPSsQixHzZl_C0LJw"
taxonomies:
  author: authors
